### ISSUE TITLE
java.lang.IllegalStateException when trying to download Parquet file

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/cloud-storage-etl-udfs#12]
When trying to pull parquet data from S3, I get the following error:

[22002] VM error: 
java.lang.IllegalStateException: Socket not created by this factory
Stack trace:
org.apache.http.util.Asserts.check(Asserts.java:34)
org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435)
org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186)
org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:728)
com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3785)
com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1107)
com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1070)
org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:276)
org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:236)
org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2812)
org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100)
org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2849)
org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2831)
org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389)
com.exasol.cloudetl.bucket.Bucket.fs$lzycompute(Bucket.scala:21)
com.exasol.cloudetl.bucket.Bucket.fs(Bucket.scala:20)
com.exasol.cloudetl.bucket.Bucket.getPaths(Bucket.scala:24)
com.exasol.cloudetl.scriptclasses.ImportMetadata$.run(ImportMetadata.scala:24)
com.exasol.cloudetl.scriptclasses.ImportMetadata.run(ImportMetadata.scala)
 (Session: 1619744297144393908)

**Comment by morazow** [comment]
Hello @exaValerieWiedemann,

Thanks for reporting this issue!

This is because the `hadoop-aws:2.8.4` version uses `aws-java-sdk` version 1.10.x. Updating `hadoop-aws` to 2.9.2 solves the problem. 

I am going to perform a new release soon.
