### ISSUE TITLE
Support writing parquet files to cloud storage

### ISSUE THREAD

**Issue by blunghamer** [exasol/cloud-storage-etl-udfs#14]
### Support writing queries / tables directly to parquet files in cloud storage accounts

Apologies, this is more a feature request than an issue: 
- Is direct support for writing parquet to cloud storage a planned feature of this repository? 

#### Rationale 
- Increases interoperabilty with data lake architectures
- In addition directly creating parquest files from scripting would enable easier integration in existing etl jobs and etl/elt infrastructure
- Simplifies architecture as there is no need for an external process doing the work
- Simplifies deployment as it avoids the hassle of extensive python scripting to do the work with the burden of uploading python native libraries to ExaBucket (pyarrow, pyarrow parquet etc.)

**Comment by morazow** [comment]
Hey @blunghamer,

Thanks for opening this feature request! Please keep providing your feedback!

Yes, export is a planned feature.  We will also start with parquet format first. 

However, please be aware that it might take some time until it is available.

**Comment by morazow** [comment]
Hello @blunghamer,

I wanted to inform you that I have released [a new version](https://github.com/exasol/cloud-storage-etl-udfs/releases) that adds feature to export an Exasol table into AWS S3 in a Parquet format.

Please feel free to give it a try!

I am going to close this ticket soon. Please do not hesitate to open a new issue ticket if you have any questions or feedback!
