### ISSUE TITLE
Correctly import parquet date and timestamp types

### ISSUE THREAD

**Issue by morazow** [exasol/cloud-storage-etl-udfs#15]
Currently we are not able to store parquet date and timestamp types in Exasol tables when importing via a udf.

-  Able to store parquet Date into table column with Exasol Date type
- Able to store parquet Timestamp into table column with Exasol Timestamp type

Parquet logical types: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md

In summary, we should use `originalType` information in parquet `PrimitiveType` in order to determine the time related types.

- typeName = INT32 , originalType = date : should be Date
- typeName = INT64, originalType in (timestamp_micros, timestamp_millis): should be Timestamp

**Comment by drumcircle** [comment]
Could you please clarify?  If we can specify the originalType in Parquet, will the UDF cast/insert into a TIMESTAMP field?  Or must we land the data in an INTEGER field and then cast to date after?

**Comment by morazow** [comment]
Hello @drumcircle,

Yes, using original type will import into corresponding Exasol field.

For example, a parquet data with the following schema:
```
message schema {
  required binary STR (UTF8);
  required int32 DT (DATE);
  optional int64 TS (TIMESTAMP_MILLIS);
}
```
can be imported into a Exasol table with following columns and types:
```
CREATE OR REPLACE TABLE MYTABLE (
  STR VARCHAR(2000),
  DT DATE,
  TS TIMESTAMP
);     
```

You do not have to import it into general integer or long data type columns and then cast them to date or timestamp values. If the original types are defined, the udf process will convert them while importing.
