### ISSUE TITLE
Missing documentation on good default values for parallelism, number of files, file size when importing

### ISSUE THREAD

**Issue by blunghamer** [exasol/cloud-storage-etl-udfs#27]
@morazow parquet import support is ***outstanding*** as we can avoid brittle CSV processes as in the regular bulk importer.

However we have run into multiple problems during bulk loading that can be avoided by using appropriate parameters and chunking of imports. 

For example timeouts occur if we load too much with one import, memory exhaustion occurs when loading too many large parquet files in parallel, parallelism too high leads to failed import.

Thus there are at lease three tuning knobs we need set appropriately:
1. Size of the parquet input files 
2. Number of parquet input files in blob store
3. Level of parallelism

Missing Documentation Hints
1. how many blobs should we push into blob storage to help exasol process them in parallel? Large parquet files (1 Mio records, 80 cols) fail to load in parallel (memory exhaustion)
2. What is the optimum level of parallelism (how far can we push parallelism up in relation to number or cores and available memory)
3. How many records / chunks / size should we package per individual import statement?

**Comment by morazow** [comment]
Hello @blunghamer,

Thanks for your feedback! These are great points!

Currently, I am looking into similar issues, but for export as a parquet format. For example, when exporting an Exasol table with 1 billion records introduces similar memory issues.

I am going to perform similar runs for import using larger & many files.

However, alternatively, you can try out to increase the JVM heap, as:
```
%jvmoption -Xms128m -Xmx1024m;
```
on ETL scripts.

Each Exasol udf vm is started with at most `2Gb` of memory. Therefore, depending on node memory and cpu you can also increase the `PARALLELISM` parameter. 

This parallelism value (`nproc()` by default) defines the number of udf vm-s and will divide the number of files per this number.

Unfortunately, for import, we can only parallelize on the number of files on the provided path. Currently, I am not sure if the size of a file would help since we need to import a file during udfs lifecycle.

**Comment by morazow** [comment]
Hello @blunghamer,

I released a new version some minutes ago. One of the changes includes the import improvements. 

General best practice is to multiply `nproc()` with the number of cores in the datanode. For example, if each datanode has 4 cores, it is good idea to set the parallelism to `nproc() * 4`.

Please give it a try and please do not hesitate to let us know if there are any issues.

I also did some tests using several file counts and file sizes for importing parquet data.

### Benchmarking Parquet Import

The total number of records in a bucket is 1 Billion, each row has 7 columns.

#### Setup

3 AWS EC2 `m4.xlarge` instances.

#### Create table statement

```sql
CREATE TABLE TABLE1 (
  C1 DOUBLE,
  C2 DOUBLE,
  C3 INTEGER,
  C4 INTEGER,
  C5 INTEGER,
  C6 VARCHAR(5),
  C7 BOOLEAN
); 
```

#### Import script

```bash
IMPORT INTO BENCH.TABLE1
FROM SCRIPT ETL.IMPORT_PATH WITH
  BUCKET_PATH    = 's3a://exa-mo-frankfurt/import/test/*'
  S3_ACCESS_KEY  = 'REDACTED'
  S3_SECRET_KEY  = 'REDACTED'
  S3_ENDPOINT    = 's3.eu-central-1.amazonaws.com'
  PARALLELISM    = 'nproc()*4';

SELECT * FROM BENCH.TABLE1 LIMIT 10;
```

Some logs on file distribution per node and vm (from test1):
```
INFO ImportFiles$: The total number of files for node: 2, vm: 140212822305968 is '42'.
INFO ImportFiles$: The total number of files for node: 1, vm: 139808459763152 is '42'.
INFO ImportFiles$: The total number of files for node: 2, vm: 140212822305952 is '42'.
INFO ImportFiles$: The total number of files for node: 1, vm: 139808459763144 is '42'.
INFO ImportFiles$: The total number of files for node: 2, vm: 140212822305976 is '42'.
INFO ImportFiles$: The total number of files for node: 0, vm: 140405257362344 is '42'.
INFO ImportFiles$: The total number of files for node: 0, vm: 140405257362360 is '42'.
INFO ImportFiles$: The total number of files for node: 1, vm: 139808459763136 is '42'.
INFO ImportFiles$: The total number of files for node: 1, vm: 139808459763160 is '42'.
INFO ImportFiles$: The total number of files for node: 2, vm: 140212822305960 is '42'.
INFO ImportFiles$: The total number of files for node: 0, vm: 140405257362336 is '42'.
INFO ImportFiles$: The total number of files for node: 0, vm: 140405257362352 is '42'.
```

#### Results

| Testname | Number of files | Each file size on disk (in MB) | Duration to import (wall clock) |
| ------------- | -------------------- | --------------------------------------- | -------------------------------- |
| Test1        | 504                   | 30.5 MB                                  | `~12 minutes`                 | 
| Test2        | 216                   | 76.3 MB                                  | `~12 minutes`                 |
| Test3        | 120                   | 152.7 MB                                | `~13 minutes`                 |
| Test4        | 60                     | 305.3 MB                                | `~14 minutes`                 |

**Comment by morazow** [comment]
Hello @blunghamer,

Were you able to try out the latest release version?

Please let me know if you have any issues, questions or requests!

**Comment by blunghamer** [comment]
Hello @morazow this really looks good, configuration is much clearer now to us.

Even before, we were already able to do bulk unloads and loads via blob storage. We just need to control the file sizes so that they are more or less uniform. We will test the new version when time permits

**Comment by morazow** [comment]
Hey @blunghamer,
I am going to close this issue. Please feel free to open a new tickets if there are anything I can help with.
