### ISSUE TITLE
Add support for Delta format

### ISSUE THREAD

**Issue by francescomucio** [exasol/cloud-storage-etl-udfs#31]
Support for the new opensource [Delta](https://delta.io/) format.

**Comment by morazow** [comment]
Hello @francescomucio,

Thanks for the suggestion!

Delta format is quite new and interesting! It seems very similar to [Apache Iceberg](https://iceberg.apache.org/) initiative.

Currently, I am not if it is possible to support it; however, I am going to look into it.

**Comment by francescomucio** [comment]
Thanks a lot. Yes, it is similar to Iceberg, but because it is pushed by a company (Databricks) it seems to have more momentum than Iceberg.
