### ISSUE TITLE
Parameter to overwrite s3 path when exporting to s3 

### ISSUE THREAD

**Issue by belenaj** [exasol/cloud-storage-etl-udfs#36]
As a user of cloud-storage-etl-udfs,
I want to be able to customise the export so that a second run on the same `BUCKET_PATH` overwrites the contents of such path instead of adding new `exa_export_N` files.

This is useful when your `BUCKET_PATH` is partitioned as `s3a://my-bucket/parquet/export/sales_positions/YYYYMMDD/`and you want to reprocess one day.

Example call:
```
EXPORT SALES_POSITIONS
INTO SCRIPT ETL.EXPORT_PATH WITH
  BUCKET_PATH    = 's3a://my-bucket/parquet/export/sales_positions/'
  OVERWRITE_PATH  = true
  S3_ACCESS_KEY  = 'MY_AWS_ACCESS_KEY'
  S3_SECRET_KEY  = 'MY_AWS_SECRET_KEY'
  S3_ENDPOINT    = 's3.MY_REGION.amazonaws.com'
  PARALLELISM    = 'iproc(), floor(random()*4)';
```

**Comment by morazow** [comment]
Hello @belenaj,

Thanks for your feedback!

That is good idea! Since we already create a filesystem object, it should be possible to delete the path if it exists.

I will try to prioritize these for the future releases.

Please do not hesitate to open Github issue or reach out if there are any other issues!

**Comment by belenaj** [comment]
hi @morazow ,
do you have any estimated release dates for this feature?
thanks!

**Comment by morazow** [comment]
Hey @belenaj,

Sorry, no estimation at the moment. Since you are asking again about it, we can plan it as one of the next tasks for the coming weeks. :)

Thanks for collaboration and feedback!

**Comment by belenaj** [comment]
yes please! this would be very helpful for us since now we have manually to delete the bucket path before exporting to make sure we dont generate dups.

Thanks!

**Comment by morazow** [comment]
Hey @belenaj,

The recent release version adds a user `overwrite` parameter to remove files from the export path.

Please give it a try!

**Comment by belenaj** [comment]
Hi @morazow I guess we can close this issue now?

Regards,
J.

**Comment by morazow** [comment]
Yes, correct.
