### ISSUE TITLE
Update User Guide Documentation

### ISSUE THREAD

**Issue by belenaj** [exasol/cloud-storage-etl-udfs#66]
After the new 0.6.0 release, user guide seems outdated. (How to use import/export functions)
CONNECTION_NAME
https://github.com/exasol/cloud-storage-etl-udfs/blob/master/docs/user_guide.md

**Comment by morazow** [comment]
Hey @belenaj,

Thanks for the feedback!

The one in the user guide seems to be an example. The usage for connection object are available in [cloud_storages.md](https://github.com/exasol/cloud-storage-etl-udfs/blob/master/docs/storage/cloud_storages.md).

**Comment by belenaj** [comment]
True! 
I checked the wrong file, thanks!

**Comment by dmitry-lu** [comment]
Hi @morazow 
I had the same question as #belenaj and wanted to open a similar ticket. And then found out that the topic #66 was already created.
As two people had the same idea - I'm proposing a change #76

**Comment by morazow** [comment]
Hello @dmitry-lu, @belenaj 

I have merged it. Thanks for the feedback and pull request!

**Comment by morazow** [comment]
Okay, I learned that this was due to the recent Github change.
- https://github.com/pandas-dev/pandas/issues/32457

It has already outrages most of the open-source ecosystem. I hope they update this change to include the original author.

Anyway, please send me the email you have used with the Github, then I can amend the commit author.

**Comment by tkilias** [comment]
@morazow Github wanted to revert this change. See [here](https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/td-p/48797/page/2) for more details.

**Comment by morazow** [comment]
Hey @tkilias ,

Great! Okay, let me wait a while, maybe the authorship automatically assigned.

**Comment by tkilias** [comment]
@morazow Unfortunately, this won't fix existing squashed merges. So, if you already merged, than you need to amend the commit.

**Comment by morazow** [comment]
@tkilias, okay that is good to know. Then, I will do that once the @dmitry-lu sends his email.

**Comment by dmitry-lu** [comment]
Hi @morazow 

Thank you for the noting this and for raising the topic, it's very thoughtful of you!
:thumbsup:
I will ping you via your exasol mail.
