### ISSUE TITLE
Azure Data Lake Gen2 Storage Import/Export

### ISSUE THREAD

**Issue by DianaGomesdeSouza** [exasol/cloud-storage-etl-udfs#86]
Hi I am trying to set up a connection between Exasol and Azure Data Lake Gen2 Storage following the set up suggested here but  it doesn't seems to work.
The main problem seems to be the bucket path

Using the
**BUCKET_PATH = 'abfs://<AZURE_CONTAINER_NAME>/***BlobPath***@<AZURE_ACCOUNT_NAME>.dfs.core.windows.net/import/orc/*'**

I got the error: 

SQL Error [22002]: VM error: 
abfs://AZURE_CONTAINER_NAME><BlobPath>@<AZURE_ACCOUNT_NAME>.dfs.core.windows.net/export/parquet has invalid authority.
Stack trace:
org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.authorityParts(AzureBlobFileSystemStore.java:187)
org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:134)
org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:104)
org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
com.exasol.cloudetl.bucket.Bucket.fileSystem$lzycompute(Bucket.scala:66)
com.exasol.cloudetl.bucket.Bucket.fileSystem(Bucket.scala:65)
com.exasol.cloudetl.bucket.Bucket.getPaths(Bucket.scala:75)
com.exasol.cloudetl.scriptclasses.ImportMetadata$.run(ImportMetadata.scala:22)
com.exasol.cloudetl.scriptclasses.ImportMetadata.run(ImportMetadata.scala)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.run(ExaWrapper.java:186) (Session: xx)

Using: 

BUCKET_PATH = **'abfs://<AZURE_CONTAINER_NAME>@<AZURE_ACCOUNT_NAME>.dfs.core.windows.net/***BlobPath***/import/orc/*'**

The Import/Exports runs with no error, but doesn't load any data.

for security reasons I am not publishing my  <AZURE_CONTAINER_NAME> and <AZURE_ACCOUNT_NAME>

Any suggestions?

Many thanks,

Diana Gomes

**Comment by morazow** [comment]
Hello @DianaGomesdeSouza ,

Thanks for the feedback!

Could you please check that Azure account name can access the sub-directories inside the container? Usually you have to enable it, so that folders inside the container is accessible.

The bucket path should include the directory paths with parquet or orc files.

For example in order to import orc files:
```
BUCKET_PATH = 'abfs://<AZURE_CONTAINER_NAME>@<AZURE_ACCOUNT_NAME>.dfs.core.windows.net/path/to/blob/files/*'
```
Where the `/path/to/blob/files/` is directory with orc files inside the container.

Similarly for export you can define different directory that will export parquet files.

**Comment by morazow** [comment]
Hello @DianaGomesdeSouza,

Since we solved the issues in the call, could we close this issue?

Please do not hesitate to open another if there any issues.

**Comment by DianaGomesdeSouza** [comment]
Hi @morazow thank you for your help, I am closing this issue.
